language: node_js

node_js:
  - "6.1"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install -g yarn

script:
  - yarn run cover

branches:
  only:
    - master
